## Spring
spring:
  # JPA
  jpa:
    properties:
      hibernate:
        show_sql: false
  # Datasource
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
